version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Preparing build...
      - python manage.py collectstatic --noinput

  build:
    commands:
      - echo Building the Django application...
      - python manage.py test  # Run tests (optional)
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
